Added apk upgrade before installation of packages
squidfunk/mkdocs-material pull request #2436
Opened 2021-03-13 14:55 UTC by tan31989

Fixes #2435

This PR is a simple fix for upgrading the apk to take the latest libraries upgraded with fixes for vulnerabilities.

Please do let me know if there is anything else that I can assist with the overall fix for docker vulnerabilities. 

After running the [trivy](https://github.com/aquasecurity/trivy) scan again, the vulnerabilities have reduced to 0.

2021-03-13 15:00 UTC, squidfunk commented
Could you check whether your change does increase the size of the image? We have to make sure that there are no apk caches inside the bundle.

2021-03-13 15:17 UTC, tan31989 commented
Sure, with master branch the image size is coming up to:

```sh
# docker images
REPOSITORY                                       TAG       IMAGE ID       CREATED          SIZE
mkdocs-material                                  latest    853ed803d91b   57 minutes ago   105MB
```

With this CURRENT branch and the latest dockerfile changes its coming as:

```sh
# docker images
REPOSITORY                                       TAG       IMAGE ID       CREATED          SIZE
mkdocs-material                                  latest    473e57c8e2b8   50 minutes ago   85.1MB
```

2021-03-13 15:29 UTC, squidfunk commented
Thanks for investigating. We need to keep the image size at the current value, as a 20-25% increase isn't great. Could you please investigate what drives this increase and mitigate it? Installing more recent versions of a few libraries shouldn't blow up the size.

2021-03-13 15:29 UTC, squidfunk requested changes
Image size should not increase when merging this PR.

2021-03-13 15:35 UTC, merged

2021-03-13 15:41 UTC, squidfunk commented
Now this is amazing. I've managed to reduce the compressed size of the image in 7.0.3 from 44 MB to 36 MB, but this PR even reduces it further down to 27 MB. That's super awesome!

I pushed 7.0.5 and latest again, if you re-pull them, you should see the changes of this PR!

2021-03-13 15:48 UTC, tan31989 commented
> ~Thanks for investigating. We need to keep the image size at the current value, as a 20-25% increase isn't great. Could you please investigate what drives this increase and mitigate it? Installing more recent versions of a few libraries shouldn't blow up the size.~
> 
> EDIT: wait, I messed up - it's the other way round. It's actually smaller. Why is that?

Thanks for merging :) 
The image size is smaller, could be attributed to the latest library releases which could have shelled off the actual size in their latest releases.

2021-03-15 08:45 UTC, squidfunk commented
Haha, so we were happy too early about the reduced size. What we missed in this PR was the `&&` at the end of the command you added. This swallowed the next command, which skipped installation of `openssl`, `git` and `git-fast-import`. Thus, we're back at 110 MB 😅 I realized this after [this tweet](https://twitter.com/elye_project/status/1371295001561292809)

2021-03-15 11:11 UTC, tan31989 commented
OMG!
Apologies for this mess. Somehow missed it even with my testing. Worth automating this verification.

2021-03-15 11:24 UTC, squidfunk commented
No worries, already fixed! Shit happens! 💩 😉