Fixes squidfunk/mkdocs-material#2466
squidfunk/mkdocs-material pull request #2467
Opened 2021-03-16 20:05 UTC by BenHimsel

Update base python image to 3.8.8

2021-03-17 10:39 UTC, jaceklaskowski commented
Why not 3.9.2-alpine3.13 since it's the [latest](https://hub.docker.com/_/python)?

2021-03-17 12:58 UTC, BenHimsel commented
The short answer would be my lack of knowledge. I did not know the effects of updating a minor version, but assumed that updating the latest patch version would be a safe contribution.

If updating to the latest minor version is the preferred update methodology, I would be happy to update the PR.

2021-03-17 16:11 UTC, squidfunk commented
We should update to the latest version. Could you update the PR and re-verify that building, serving, and deploying still works?

2021-03-20 12:10 UTC, squidfunk requested changes
Could you please check if we can safely update to the latest version as proposed by @jaceklaskowski?

2021-03-26 00:02 UTC, polarathene commented
I don't see this as an exploit that is relevant to the context of the docker image personally.

You already run as the root user within the docker image (and the docker daemon usually is run as root), how exactly is this attack being envisioned of being carried out, with what goal and what present access to perform it?

[Upstream notes it as](https://www.openssh.com/txt/release-8.5):

> ssh-agent(1): fixed a double-free memory corruption that was introduced in OpenSSH 8.2 . We treat all such memory faults as potentially exploitable.
>
> The most likely scenario for exploitation is a user forwarding an agent either to an account shared with a malicious user or to a host with an attacker holding root access.

Ignoring that, you can easily check what version is shipped by Alpine via [their web interface for packages](https://pkgs.alpinelinux.org/package/v3.13/main/x86_64/openssh) (3.13 provides `openssh-8.4_p1-r3`). You would need to use [`edge`](https://pkgs.alpinelinux.org/packages?name=openssh&branch=edge) (which is a bad idea) or wait until `3.14` AFAIK for openssh version 8.5.

So no, updating the image does nothing to resolve this concern even if it were valid.

2021-03-28 10:45 UTC, squidfunk commented
Superseded by 56e8162a0.

2021-03-28 10:45 UTC, closed without merging