Update Greek translation
squidfunk/mkdocs-material pull request #3191
Opened 2021-11-07 16:29 UTC by alkisg

Hi, I updated the Greek translation.
There were some missing strings, but most importantly the next/previous words were translated as previous/next.

2021-11-07 16:50 UTC, alkisg commented
@squidfunk, I need a bit of help for the Greek search function.
My attempt above ^ fails with:

> WARNING  -  [18:45:12] "GET /assets/javascripts/lunr/min/lunr.el.min.js HTTP/1.1" code 404

If I change `"search.config.lang": "en",` instead of `el`, then I can search for English strings but not for Greek strings.

I might be able to send some patch for `el` to lunr in the following months, but for now, could we somehow have Greek search working even without stemming?

2021-11-07 16:57 UTC, alkisg commented
Got it, with this additional commit Greek search works now (without stemming).

2021-11-07 17:10 UTC, squidfunk requested changes

2021-11-07 17:10 UTC, squidfunk commented on src/partials/languages/el.html
> +  "search.config.pipeline": " ",
I think the `trimmer` and `stopWordFilter` should not be removed. My testing showed it also works with them.

2021-11-07 17:14 UTC, alkisg commented
By replacing:
> "search.config.pipeline": " ",

with:
> "search.config.pipeline": "trimmer, stopWordFilter",
  
Greek search stops working for me. I'll experiment more, but if you have any hints, they'll be most welcome. :)

2021-11-07 17:16 UTC, alkisg commented
With this, it does work:

>   "search.config.pipeline": "stopWordFilter",

2021-11-07 17:23 UTC, alkisg commented
As a test case, if I have the string:
"english ελληνικά"

then typing `en` in Search always matches the text, but typing `ελ` only works if `trimmer` has been removed.

2021-11-13 07:50 UTC, squidfunk approved these changes

2021-11-13 07:52 UTC, merged