Added Google Tag Manager support
squidfunk/mkdocs-material pull request #3480
Opened 2022-01-19 20:12 UTC by gergoradeczki

Imported the JavaScript code from https://tagmanager.google.com/ with the modification to use the property id from mkdocs.yml.

2022-01-20 09:02 UTC, squidfunk commented
Thanks for the PR. You made the changes in the `material` folder, which is overwritten during build, so this won't work. Please make your changes in the `src` folder and then build the theme. This is explained in the [theme development guide](https://squidfunk.github.io/mkdocs-material/customization/#theme-development), and mentioned in the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md#submitting-a-pull-request-pr) 😉

2022-01-20 09:03 UTC, squidfunk requested changes
See above

2022-01-20 14:27 UTC, squidfunk requested changes
Site search and instant loading integration seem to be missing. Please add.

2022-01-20 15:40 UTC, gergoradeczki commented
I might be wrong but, as I understood the differences between Google Analytics and Google Tag Manager, GTM doesn't require you to explicitly add these events in code. Instead, you would have to add it through their website.

2022-01-20 16:22 UTC, squidfunk commented
Oh, okay. I'm not familiar with tag manager. So to better understand whether this PR is a good fit for the project, how would you implement site search tracking via GTM? is that possible? How does a GTM setup look like? I'd be curious to learn some more before I can decide whether we can merge this or not.

2022-01-20 23:06 UTC, gergoradeczki commented
This is what I ended up doing in order to enable tracking of users:

![image](https://user-images.githubusercontent.com/4851436/150433100-939bc5f3-7bbe-4b77-898c-1df08122ca8f.png)

In the Tags tab, I created **Google Analytics GA4 Configuration** Tag and added a Page View trigger called All Pages which from its name, fires on all pages when loaded. Then created a **History Changes** trigger in the Triggers and added it to the triggers list for the **Google Analytics GA4 Configuration**.

For the search field, I don't think I have the best solution. My solution would be to track the URL changes, then extract the ?h=string query using a variable.

![image](https://user-images.githubusercontent.com/4851436/150436102-d7bb05ea-4fb7-4d2d-bb0a-bcadd2732826.png)

2022-01-21 10:58 UTC, squidfunk commented
Thanks for the explanation. I think we can add support for GTM, but this PR still needs some work before it can be merged:

- Can we improve the docs? They only explain how to add GTM, but not what to make of it, e.g. how to achieve the same stuff as with the other integrations. We don't have to add guides explaining everything in detail, but some guidance for users in the form of recommended readings or some instructions would be beneficial. If we don't have this in the docs, users will open issues asking for them, which is more work for me in the future. Thus, please think of how we can improve the documentation so that users know what to make of GTM.

- Please format the source code so that it matches the style of the other integrations. I know that this is generated from a snippet, but I'd rather have readable, maintainable code.

2022-01-21 10:59 UTC, squidfunk requested changes

2022-01-21 10:59 UTC, squidfunk commented on docs/setup/setting-up-site-analytics.md
> +=== ":material-google-analytics: Google Tag Manager"
Please add documentation, see my last comment.

2022-01-21 10:59 UTC, squidfunk commented on src/partials/integrations/analytics/google.html
> +    (function(w, d, s, l, i) {
Please format the sources properly. Those are no good variables names.

2022-02-05 15:12 UTC, squidfunk commented
@gergoradeczki could you please make the requested changes?

2022-02-07 11:57 UTC, gergoradeczki commented
I'm not confident enough with the search query tracking solution I found and because of this I don't think the addition of GTM is a good idea.

2022-02-07 11:57 UTC, closed without merging

2022-02-07 12:46 UTC, squidfunk commented
Okay, never mind, thanks for your time!

2023-03-23 12:50 UTC, pstavirs commented
@squidfunk Any chance/plans to support Google Tag Manager? Even if search query tracking is not possible with GTM, it would be good to have it as an option for those who want to use GTM instead of GA4.

2024-02-17 07:37 UTC, minhluan259 commented
@pstavirs any update on this? Thanks.

2024-02-17 07:45 UTC, pstavirs commented
See https://github.com/squidfunk/mkdocs-material/discussions/5607

2024-02-17 07:45 UTC, squidfunk commented
@minhluan259 We currently have no plans to add it to core, but [it can be achieved with customization in 5 minutes](https://github.com/squidfunk/mkdocs-material/discussions/5607#discussioncomment-7323367).