Update Mermaid.js to version 9.0.0
squidfunk/mkdocs-material pull request #3824
Opened 2022-04-20 12:47 UTC by vectorsli

This update brings `gitGraph` to stable. Since the support for `gitGraph` wasn't advertised and this is the reason for the major version bump, it should be safe to upgrade.

**Note**: I used search + replace to change `8.13.3` to `9.0.0` for the mermaid dependency. The development environment I created locally didn't work as expected and I didn't want to debug.

2022-04-20 12:54 UTC, squidfunk commented
Thanks for the PR. However, without testing and ensuring that all graphs still work, I'm unable to merge. I might look into this in the future, but if you want your PR merged, we should make sure that this PR doesn't break anything. In essence, please provide screenshots of all graphs on the diagrams page after upgrading to 9.0.0.

2022-04-20 12:54 UTC, squidfunk requested changes
As noted.

2022-04-21 06:40 UTC, vectorsli commented
I added an example to the documentation:
![image](https://user-images.githubusercontent.com/104021830/164385047-374b5690-86f5-4350-b041-4a9f35cc628e.png)

The other diagrams look fine, too (from bottom up):
![image](https://user-images.githubusercontent.com/104021830/164385097-c3c10935-7fb1-443c-b51c-d352c91cb97d.png)
![image](https://user-images.githubusercontent.com/104021830/164385114-7e19031e-4f8c-4030-98d7-0c8b38ec542b.png)
![image](https://user-images.githubusercontent.com/104021830/164385145-e4fcc2b8-33e7-4fca-9f5a-35a4e074305f.png)
![image](https://user-images.githubusercontent.com/104021830/164385166-22a5e0b6-5166-4162-8a75-70bbd046d59a.png)
![image](https://user-images.githubusercontent.com/104021830/164385182-ad1c13ef-a8ba-41be-bba0-d7f166a0b134.png)


## Development setup

These images were created using the following dev workflow:
``` sh
npm start
mkdocs serve --watch-theme
```

Building the theme using `npm run build`/`npm run build:all` didn't work for me. The `iconsearch_index.json` wasn't generated and for some reason the html templates were referencing the non-minified versions of the assets (`bundle.js` etc.). I'm not sure what's wrong with my setup, maybe it's because I'm on Windows?
Anyway, I don't think it's useful to commit my generated files, so I'll leave the PR as it is. I hope that's okay.

2022-04-24 10:42 UTC, squidfunk requested changes
Thanks for making the changes! However, we don't want to advertise support for Git Graphs, because they have several problems when rendered, particularly sizing issues that don't work well on mobile. This is explained [here](https://facelessuser.github.io/pymdown-extensions/extras/mermaid/#practical-diagrams). Thus, the section should be removed from the documentation, or users will start to create issues because Git Graphs do not work as advertised.

2022-04-24 10:42 UTC, squidfunk commented on docs/reference/diagrams.md
> +### Using Gitgraphs
Please remove this section – we're not officially supporting this type of diagram.

2022-04-24 10:53 UTC, squidfunk commented on docs/reference/diagrams.md
> +### Using Gitgraphs
I've added a note for the other diagram types in 314bab53c.

2022-04-24 11:29 UTC, squidfunk commented
Superseded by 24025f42. I went ahead and updated to Mermaid.js 9.0.1, the latest version. Thanks again for testing the diagrams! I've discovered two more problems with arrows in dark mode that I fixed in the same commit.

2022-04-24 11:29 UTC, closed without merging

2022-04-28 09:09 UTC, vectorsli commented
Thanks for bringing this to the latest release!