Fix unicode, case-sensitive `slugify` setting in the documentation
squidfunk/mkdocs-material pull request #6988
Opened 2024-03-29 09:06 UTC by kuanyili

Unicode, case-sensitive reference setting causes error below.

```
yaml.constructor.ConstructorError: expected a mapping node, but found scalar
```

Update related sections in the documentation to address this issue.

Newer Python-Markdown has `slugify_unicode` built-in, so this

```yaml
markdown_extensions:
  - toc:
      slugify: !!python/name:markdown.extensions.toc.slugify_unicode
```

also works for case-insensitive use cases.

Fixes: ee1e675da613 ("Update slug reference")

## References

- https://pyyaml.org/wiki/PyYAMLDocumentation#objects
- https://python-markdown.github.io/extensions/toc/#usage
- https://facelessuser.github.io/pymdown-extensions/extensions/tabbed/#options

2024-03-29 23:55 UTC, squidfunk commented
Thanks for the PR. Could you please provide a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) here? Before we can consider merging a PR that fixes an error, we must first ensure that it actually is an error. This is also why, before creating an issue, we recommend to [discuss changes with us](https://squidfunk.github.io/mkdocs-material/contributing/making-a-pull-request/#preparing-changes-and-draft-pr). (info box) We cannot just change things without understanding their impact. However, in this case, you can attach the minimal reproduction which showcases the problem here. I hope you understand that with a project of this size, we have to have processes and we must ask our users to stick to them. Otherwise it would be unmanageable.

2024-03-30 00:27 UTC, kuanyili commented
Ah, totally missed that! My apologies and thanks for the pointer.

Here is the minimal reproduction.

[fix-slugify.zip](https://github.com/squidfunk/mkdocs-material/files/14809329/fix-slugify.zip)

2024-03-31 08:48 UTC, squidfunk requested changes
Thanks for the PR, cosmetic change.

@facelessuser could I ask you to look over this? I was erroneously assuming that this syntax works, but it seems we always need to provide a mapping? Can this PR be improved from your perspective?

2024-03-31 08:48 UTC, squidfunk commented on docs/setup/extensions/python-markdown.md
> +:   <!-- md:default `markdown.extensions.toc.slugify` --> This option allows for
Please don't use the fully qualified syntax here – there's no need.

2024-03-31 15:16 UTC, facelessuser commented
@squidfunk to be honest, I didn't think to explicitly document the empty parameter in case in the [FAQ](https://facelessuser.github.io/pymdown-extensions/faq/#function-references-in-yaml) 😅.

Because this `slugify_unicode` function returns the required slugify based on parameter input, if you are providing no inputs, then yes, you must use `{}` to specify no parameters.

So this for no parameters:

```yaml
slugify: !!python/object/apply:pymdownx.slugs.slugify {}
```

This to call specific keyword parameters:

```yaml
slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
```

2024-03-31 15:22 UTC, facelessuser commented
I've updated the FAQ here: [88a94636a2904c33829037369ca7155f6abc2a62](https://github.com/facelessuser/pymdown-extensions/commit/88a94636a2904c33829037369ca7155f6abc2a62)

2024-03-31 23:33 UTC, squidfunk commented
Perfect, thanks! It was a misunderstanding on my side, which led to a wrong code snippet on our documentation. This PR fixes this – thanks for you both!

2024-03-31 23:34 UTC, merged