docs(publish gitlab pages): Update publish comment on gitlab
squidfunk/mkdocs-material pull request #7853
Opened 2024-12-29 20:10 UTC by niclasheinz

I have noticed that since a few GitLab releases, unique domains are used by default for GitLab Pages deployments, for example `https://website-5c034c.gitlab.io/` instead of niclasheinz.gitlab.io/website. I have written a small blog post that helps users to use the desired domain.

2024-12-30 08:42 UTC, squidfunk commented
Thanks for the PR. Is this also true for GitLab's hosted offering, or only for on-premise installations?

2024-12-30 09:12 UTC, niclasheinz commented
I found it on gitlab.com (SaaS)

2024-12-30 10:02 UTC, squidfunk commented
Thanks! So if it's such a central thing, I think it would be a better idea to list the steps that you listed in your blog post directly on our publishing guide, so we can keep the AX better – less indirection. If and only if this is okay for you.

2024-12-30 10:32 UTC, squidfunk commented
Just under the code block is fine. I think we can limit it to something like (extracted from your article):

```
CODE BLOCK

${Insert 1 sentence explanation on domain names}. To switch from a unique domain to the traditional URL structure, follow these steps:

1. Locate Your Repository
2. Go to Settings > Pages in the repository menu.
3. In the Unique domain settings section, uncheck the box labeled Use unique domain.
4. Click Save changes to apply the update.

Now, you ...
```

2024-12-30 13:09 UTC, squidfunk commented
No, please just use verbatim text. It's not a recommendation, but the expected outcome (= users will 99% want a proper URL, and not a random identifier), so it should be part of the normal flow.

2024-12-30 15:37 UTC, niclasheinz commented
@squidfunk it's ready for review.

2024-12-30 16:08 UTC, squidfunk requested changes
Only some minor changes related to formatting  ☺️

2024-12-30 16:08 UTC, squidfunk commented on docs/publishing-your-site.md
> +2.    Go to **Settings > Pages** in the repository menu.
Please use consistent spacing in lists

2024-12-30 16:08 UTC, squidfunk commented on docs/publishing-your-site.md
> +Your documentation is not published under `<username>.gitlab.io/<repository>` by default since **GitLab 17.4** [^1]. However, if you prefer a cleaner URL structure, such as `<username>.gitlab.io/<rep
Please break lines at 80 characters, as the rest of the document

2024-12-30 16:08 UTC, squidfunk commented on docs/publishing-your-site.md
> +2.    Go to **Settings > Pages** in the repository menu.
Please use a chevron here: ›

2024-12-30 16:08 UTC, squidfunk commented on docs/publishing-your-site.md
> +[^1]: [Release notes for Gitlab 17.4](https://about.gitlab.com/releases/2024/09/19/gitlab-17-4-released/)
Please add a newline between the next headline and the footnote

2024-12-30 16:26 UTC, niclasheinz commented
I solved the styling issues

2024-12-31 08:15 UTC, squidfunk commented
Perfect, thanks for your work!

2024-12-31 08:16 UTC, merged

2024-12-31 08:49 UTC, niclasheinz commented
You're welcome. Happy new year!

2024-12-31 08:55 UTC, squidfunk commented
Happy new year to you too!